# install
- name: Install this role on {{ansible_os_family}}
  include: "{{ansible_os_family}}.yml"

# configure
- name: setting neo4j
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '#dbms.default_listen_address=0.0.0.0'
    line: "dbms.default_listen_address=0.0.0.0"
    state: present
  when: neo4j_version != "3.5"
    
- name: setting neo4j
  lineinfile:
    dest: /etc/neo4j/neo4j.conf
    regexp: '#dbms.connector.bolt.listen_address=:7687'
    line: "dbms.connector.bolt.listen_address=0.0.0.0:7687"
    state: present
  when: neo4j_version == "3.5"

- name: Set default password for user neo4j before starting up the database for the first time
  shell: neo4j-admin set-initial-password {{neo4j_root_password}}
      
- name: Restart neo4j
  service: name=neo4j state=restarted enabled=yes

# add soft link
- name: Create link  
  file:
    src: '{{item.src}}'
    dest: '{{item.dest}}'
    state: link
  with_items:
    - {src: /var/lib/neo4j/,dest: /data/neo4j}
    - {src: /etc/neo4j/neo4j.conf,dest: /data/neo4j/neo4j.conf}
    - {src: /etc/neo4j/neo4j.conf,dest: /data/config/neo4j.conf}
    - {src: /var/log/neo4j/,dest: /data/neo4j/log}
    - {src: /var/log/neo4j/,dest: /data/logs/neo4j}

# print version
- block:
  - name: Check Neo4j Version
    shell: sudo sh -c "neo4j version 1>> /data/logs/install_version.txt"
