- name: Add Neo4j repositories
  yum_repository:
    name: neo4j
    file: neo4j
    description: Neo4j RPM Repository
    baseurl: https://yum.neo4j.com/stable
    gpgcheck: yes
    gpgkey: https://debian.neo4j.com/neotechnology.gpg.key
    enabled: yes

- name: Install Neo4j
  yum:
    name: "neo4j-{{neo4j_version_meta[neo4j_version].RedHat}}"
    
